### ISSUE TITLE
扫码崩溃问题

### ISSUE THREAD

**Issue by ljp2017** [devilsen/CZXing#100]
pid: 7222, tid: 7307, name: Thread-270  >>> me.devilsen.czxing <<<
03-10 15:06:31.364 159-159/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadbaad
03-10 15:06:31.397 159-159/? I/DEBUG: Abort message: 'invalid address or address of corrupt block 0xb8829538 passed to dlfree'
03-10 15:06:31.397 159-159/? I/DEBUG:     r0 00000000  r1 a05079d8  r2 deadbaad  r3 00000000
03-10 15:06:31.397 159-159/? I/DEBUG:     r4 b8829538  r5 b6eba0e8  r6 9ec96000  r7 b8829540
03-10 15:06:31.397 159-159/? I/DEBUG:     r8 a0507f20  r9 b87fb0b8  sl a0507ea0  fp b87fb0b8
03-10 15:06:31.397 159-159/? I/DEBUG:     ip b6eb464c  sp a0507dc8  lr b6e88f4b  pc b6e88f4c  cpsr 60070030
03-10 15:06:31.397 159-159/? I/DEBUG: backtrace:
03-10 15:06:31.397 159-159/? I/DEBUG:     #00 pc 0002bf4c  /system/lib/libc.so (dlfree+1239)
03-10 15:06:31.398 159-159/? I/DEBUG:     #01 pc 00012257  /system/lib/libc.so (free+10)
03-10 15:06:31.398 159-159/? I/DEBUG:     #02 pc 000e4a7d  /data/app/me.devilsen.czxing-2/lib/arm/libczxing.so (ImageScheduler::~ImageScheduler()+280)
03-10 15:06:31.398 159-159/? I/DEBUG:     #03 pc 000f9f7b  /data/app/me.devilsen.czxing-2/lib/arm/libczxing.so (Java_me_devilsen_czxing_code_NativeSdk_destroyInstance+58)
03-10 15:06:31.398 159-159/? I/DEBUG:     #04 pc 000a2fa1  /system/lib/libart.so (art_quick_generic_jni_trampoline+32)
03-10 15:06:31.398 159-159/? I/DEBUG:     #05 pc 000649fc  /dev/ashmem/dalvik-non moving space (deleted)

**Comment by xleo1989** [comment]
也碰到了同样的bug，老旧的手机和平板上容易重现，比如：乐视手机 乐1 型号x600 android版本6.0

**Comment by xleo1989** [comment]
android 6.0 /6.0.1

**Comment by devilsen** [comment]
fix by @xleo1989 https://github.com/devilsen/CZXing/commit/a2489ea41f5d0ffb639ddb98e4407b99581614c3
