### ISSUE TITLE
只能识别简单的图片二维码，复杂点的识别不了

### ISSUE THREAD

**Issue by fylw** [devilsen/CZXing#101]
只能识别简单的图片二维码，复杂点的识别不了，图片中的小二维码识别不了，多个二维码也识别不了，不知道像微信那种长图都能够识别出来是怎么做到的

**Comment by devilsen** [comment]
我在测试中使用的都是比较复杂的二维码，都是可以识别的呀，你的二维码是什么样子的，可以发出来参考一下。

**Comment by fylw** [comment]
editToReview
![image](https://user-images.githubusercontent.com/5906740/76731456-7131cb00-6798-11ea-8e09-9a5fd0ee352b.png)
![image](https://user-images.githubusercontent.com/5906740/76731466-7727ac00-6798-11ea-8a8a-bfa040183505.png)
还有微信的超长图

**Comment by devilsen** [comment]
@fylw 这两个图片我都测试通过了，你可以用新版的再试下。
