### ISSUE TITLE
三星Galaxy S7出现警告: 释放相机时提示相机正在被使用。

### ISSUE THREAD

**Issue by 243573077** [devilsen/CZXing#103]
在三星Galaxy S7，扫描二维码后成功展示结果，但logcat中显示日志如下：
![log72720](https://user-images.githubusercontent.com/4500285/76742022-6e8ca100-67ab-11ea-99be-75cc7c9a7a88.png)
该日志是CameraSurface.java的171行调用mCamera.cancelAutoFocus()抛出。
查看网上解决办法，说是在CameraSurface.java文件surfaceDestroyed(SurfaceHolder holder)方法中，增加一句holder.removeCallback(this);

最后 为了防止日志图片丢失，这里也上传log文本内容：
System.err: java.lang.RuntimeException: Camera is being used after Camera.release() was called
System.err:     at android.hardware.Camera.native_cancelAutoFocus(Native Method)
System.err:     at android.hardware.Camera.cancelAutoFocus(Camera.java:1314)
System.err:     at me.devilsen.czxing.camera.CameraSurface.stopCameraPreview(CameraSurface.java:171)
System.err:     at me.devilsen.czxing.camera.CameraSurface.surfaceDestroyed(CameraSurface.java:90)
System.err:     at android.view.SurfaceView.updateWindow(SurfaceView.java:636)
System.err:     at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:266)
System.err:     at android.view.View.dispatchWindowVisibilityChanged(View.java:11091)
System.err:     at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
System.err:     at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
System.err:     at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
System.err:     at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
System.err:     at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1798)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1502)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7044)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:702)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:638)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6646)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
com.qrcode.demo D/ViewRootImpl@c89072e[ScanActivity]: MSG_WINDOW_FOCUS_CHANGED 0

**Comment by devilsen** [comment]
已修复 https://github.com/devilsen/CZXing/commit/36da03a506f174d6726d3bcfae6f8e84287e845e
