### ISSUE TITLE
仅使用v7a 时闪退

### ISSUE THREAD

**Issue by xleo1989** [devilsen/CZXing#104]
![Uploading image.png…]()

**Comment by xleo1989** [comment]
#00 pc 00016c68 /system/lib/libc.so (__memcpy_base+232) [armeabi-v7a]
--
2 #01 pc 0022f7f3 /data/app/com.xinheyun.scanner2_example-1/lib/arm/libczxing.so (cv::Mat::copyTo(cv::_OutputArray const&) const+566) [armeabi-v7a]
3 #02 pc 001b877d /data/app/com.xinheyun.scanner2_example-1/lib/arm/libczxing.so [armeabi-v7a]
4 #03 pc 001a4151 /data/app/com.xinheyun.scanner2_example-1/lib/arm/libczxing.so (cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)+1320) [armeabi-v7a]
5 #04 pc 000f2433 /data/app/com.xinheyun.scanner2_example-1/lib/arm/libczxing.so (ImageScheduler::preTreatMat(FrameData*)+134) [armeabi-v7a]

**Comment by devilsen** [comment]
已修复 https://github.com/devilsen/CZXing/commit/f3956a684089fba5ab4c565865ac4eeb5c35beb2
