### ISSUE TITLE
有两个疑问

### ISSUE THREAD

**Issue by wangxp423** [devilsen/CZXing#107]
1，你这个库也是基于zxing然后自己又做了很多优化对吗？
2，使用了你这个依赖库apk包是不是要增大好几M?

**Comment by wangxp423** [comment]
还有一个问题，现在主流的cpu架构主要是armeabi-v7a和arm64-v8a我看你的c++也支持这两种.so文件，如果两种都选势必是造成包大小的翻倍增加，如果选其中一种都有可能对另一种架构的机型造成适配缺失，但是armeabi却同时兼容以上两种。为什么没有考虑增加一个armeabi的配置呢？

**Comment by 1976222027** [comment]
1对焦才能获取最清晰画面，
2 识别图形的准确率

**Comment by 1976222027** [comment]
armeabi 是2007年左右的产物，世面已弃用
