### ISSUE TITLE
1.0版本扫码直接崩溃了，每次都是

### ISSUE THREAD

**Issue by FrankLove** [devilsen/CZXing#108]
你好，下载1.0的apk安装的华为M3平板上，点击“调用api打开界面"扫码，扫码后直接崩溃了，并且还是必崩溃，试了几次都如此。自定义扫码界面却没有崩溃，可以正常运行

**Comment by BeyondWorlds** [comment]
我也遇到了：
build.gradle只添加： abiFilters 'armeabi-v7a' 是可以的，再添加其他的就会崩溃：比如arm64-v8a，测试机型红米4A;(生成二维码和扫码都会崩溃)，自定义扫码没问题

#00 pc 0000000000024984 /system/lib64/libc.so (mbsnrtowcs+184) [arm64-v8a::6aa79b364fc5f9f304543074b2fbd52f]
#1 pc 00000000000c81cc /data/app/me.devilsen.czxing-1/lib/arm64/libczxing.so (_Z13ANSIToUnicodeRKNSt6__ndk112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE+132) [arm64-v8a::5c21b1e9ed6d033a79f9554e24d47d30]
#2 pc 00000000000cada4 /data/app/me.devilsen.czxing-1/lib/arm64/libczxing.so (Java_me_devilsen_czxing_code_NativeSdk_writeCode+264) [arm64-v8a::5c21b1e9ed6d033a79f9554e24d47d30]
#3 pc 0000000000cac878 /data/app/me.devilsen.czxing-1/oat/arm64/base.odex (oatexec+4323448) [arm64-v8a::f89852c6b5158dbaf6b5b3d1234f8087]

**Comment by devilsen** [comment]
@FrankLove 上传了新版本，再试试

**Comment by FrankLove** [comment]
> @FrankLove 上传了新版本，再试试
还是一样会崩溃

**Comment by FrankLove** [comment]
> @FrankLove 上传了新版本，再试试
还是一样会崩溃

**Comment by devilsen** [comment]
> > @FrankLove 上传了新版本，再试试
> > 还是一样会崩溃

发一下崩溃Log，我具体查一下
