### ISSUE TITLE
识别率很高，就是反色二维码扫不出来

### ISSUE THREAD

**Issue by uCloudCastle** [devilsen/CZXing#112]

**Comment by devilsen** [comment]
反色是指黑白位置颠倒的吗？发一张图看下。

**Comment by uCloudCastle** [comment]
> 反色是指黑白位置颠倒的吗？发一张图看下。

类似这样的
![B41881B5-9648-45c5-9B07-7580748E69D5](https://user-images.githubusercontent.com/7778471/82984899-9f981600-a025-11ea-9fe6-ad9fead67afa.png)

**Comment by devilsen** [comment]
已添加此功能
