### ISSUE TITLE
集成后包太大，有没有办法解决或思路

### ISSUE THREAD

**Issue by heiguigui** [devilsen/CZXing#117]

**Comment by heiguigui** [comment]
能把opencv的包缩减一下么，一个扫描功能增加6、7兆有点鸡肋

**Comment by devilsen** [comment]
现在的包已经精简了很多了，暂时还没办法减小，我测试的过程中如果添加 armeabi-v7a 会增加2.2M，如果使用arm64会增加2.7M，这还是测试环境，如果在release包中会更小，如果能提升扫码效率，我觉得是可以接受的。
