### ISSUE TITLE
oppoA37m android5.0 各种崩溃

### ISSUE THREAD

**Issue by itwangyong** [devilsen/CZXing#118]

**Comment by devilsen** [comment]
崩溃日志贴一下 @itwangyong

**Comment by lianaidi** [comment]
#01     pc 00000000000c81cc     /data/app/com.daylong.wunder-1/lib/arm64/libczxing.so  (ANSIToUnicode(std::__ndk1::basic_string<char,  std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>  > const&)+132) [arm64-v8a]
--
3 #02     pc 00000000000cada4     /data/app/com.daylong.wunder-1/lib/arm64/libczxing.so  (Java_me_devilsen_czxing_code_NativeSdk_writeCode+264) [arm64-v8a]
4 #03    pc 00000000017074b4    /data/dalvik-cache/arm64/data@app@com.daylong.wunder-1@base.apk@classes.dex (oatdata+24143028) []
5 java:
6 me.devilsen.czxing.code.BarcodeWriter.write(BarcodeWriter.java:103)
7 me.devilsen.czxing.code.BarcodeWriter.write(BarcodeWriter.java:49)
8 me.devilsen.czxing.code.BarcodeWriter.write(BarcodeWriter.java:36)
9 com.dalong.baselibrary.util.img.ImageUtil$1.onResourceReady(ImageUtil.java:83)
10 com.dalong.baselibrary.util.img.ImageUtil$1.onResourceReady(ImageUtil.java:61)
11 com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:582)
12 com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:544)
13 com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:152)
14 com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:398)
15 android.os.Handler.handleCallback(Handler.java:739)
16 android.os.Handler.dispatchMessage(Handler.java:95)
17 android.os.Looper.loop(Looper.java:135)
18 android.app.ActivityThread.main(ActivityThread.java:5418)
19 java.lang.reflect.Method.invoke(Native Method)
20 java.lang.reflect.Method.invoke(Method.java:372)
21 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
22 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by lianaidi** [comment]
@devilsen
