### ISSUE TITLE
二次打开扫描页面出现错误

### ISSUE THREAD

**Issue by JiangXianKaiNan** [devilsen/CZXing#12]
打开扫描页面什么都不扫描关闭页面紧接着在次打开就会出现无法打开相机的错误，是不是我哪里写的不对呢

**Comment by JiangXianKaiNan** [comment]
。

**Comment by devilsen** [comment]
相机对于生命周期的要求很严苛，最好参考[ScanActivity](https://github.com/devilsen/CZXing/blob/master/czxing/src/main/java/me/devilsen/czxing/ScanActivity.java)原封不动把ScanView的生命周期接管。

**Comment by JiangXianKaiNan** [comment]
我是直接参考ScanActivity原封不动把ScanView的生命周期接管 。
（我的浏览器不知道什么原因上传不了图片，没办法在这里直接上传图片）
好像是相机关闭时没有关闭掉，在次打开时出的错误   BarCoderView类中的startCameraById方法返回的错误

**Comment by devilsen** [comment]
直接安装release包会出问题吗？如果不行的话，说下使用的手机，我具体测下。

**Comment by JiangXianKaiNan** [comment]
复现方式，就是在10秒内在次打开扫描页面时会出错。  我们用的定制Pad，Android系统版本在5.1~7都有。
     这个问题不会影响我们流程上的正常使用，只是偶然发现的

**Comment by devilsen** [comment]
这个问题在刚开发的时候，在华为手机上确实遇到过，不过后来解决了，不知道你的是因为定制的原因还是程序上的问题。

**Comment by JiangXianKaiNan** [comment]
程序上看代码跟ScanActivity没区别该加的都加了，估计是定制问题。
Pad上能用就行，我们的流程也就用一次两次的其它时间很少会用到
