### ISSUE TITLE
扫描结果会乱码

### ISSUE THREAD

**Issue by pgn625007369** [devilsen/CZXing#121]
在哪里修改可以加入编码方式?

**Comment by devilsen** [comment]
编码是在 C 里面转换的，一些手机一直崩溃，这次使用了 zxing 内置的方法，竟然乱码了。。
你用的什么手机？我查一下有没有其他的解决方案。

**Comment by pgn625007369** [comment]
不关手机问题吧 可能要修改zxing内部代码了

**Comment by pgn625007369** [comment]
![WechatIMG64](https://user-images.githubusercontent.com/15341432/91541031-4904e580-e94e-11ea-8be8-fe6776f41c99.jpeg)
譬如这张图片到内容解释就有乱码了

**Comment by devilsen** [comment]
已修复
