### ISSUE TITLE
生成二维码

### ISSUE THREAD

**Issue by 1lyy2** [devilsen/CZXing#122]
调用二维码生成，报找不到.so文件  

couldn't find "libczxing.so"

**Comment by devilsen** [comment]
clean一下试试，我看打的包里是有 so 文件的

**Comment by 1lyy2** [comment]
还是不行的，之前都没用到生成二维码的，现在用到就发现，难道是我哪里没配置对吗？扫码的功能都正常可用

020-08-27 10:16:53.516 25839-25839/com.douyue.app E/AndroidRuntime: FATAL EXCEPTION: main
&nbsp; &nbsp; Process: com.douyue.app, PID: 25839
&nbsp; &nbsp; java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.douyue.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.douyue.app-1/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libczxing.so"
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.Runtime.loadLibrary0(Runtime.java:972)
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.System.loadLibrary(System.java:1530)
&nbsp; &nbsp; &nbsp; &nbsp; at me.devilsen.czxing.code.NativeSdk.<clinit&gt;(NativeSdk.java:83)
&nbsp; &nbsp; &nbsp; &nbsp; at me.devilsen.czxing.code.NativeSdk.getInstance(NativeSdk.java:17)
&nbsp; &nbsp; &nbsp; &nbsp; at me.devilsen.czxing.code.BarcodeWriter.write(BarcodeWriter.java:103)
&nbsp; &nbsp; &nbsp; &nbsp; at me.devilsen.czxing.code.BarcodeWriter.write(BarcodeWriter.java:49)
&nbsp; &nbsp; &nbsp; &nbsp; at com.douyue.app_main.dialog.PositionShareDialog$Builder.createQR(PositionShareDialog.java:80)
&nbsp; &nbsp; &nbsp; &nbsp; at com.douyue.app_main.dialog.PositionShareDialog$Builder.<init&gt;(PositionShareDialog.java:60)
&nbsp; &nbsp; &nbsp; &nbsp; at com.douyue.app_main.fragment.trade.MyPositionFragment.onItemChildClick(MyPositionFragment.java:208)
&nbsp; &nbsp; &nbsp; &nbsp; at com.chad.library.adapter.base.BaseQuickAdapter.setOnItemChildClick(BaseQuickAdapter.kt:612)
&nbsp; &nbsp; &nbsp; &nbsp; at com.chad.library.adapter.base.BaseQuickAdapter$bindViewClickListener$$inlined$let$lambda$3.onClick(BaseQuickAdapter.kt:564)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.View.performClick(View.java:5610)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.View$PerformClick.run(View.java:22265)
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.Handler.handleCallback(Handler.java:751)
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.Handler.dispatchMessage(Handler.java:95)
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.Looper.loop(Looper.java:154)
&nbsp; &nbsp; &nbsp; &nbsp; at android.app.ActivityThread.main(ActivityThread.java:6077)
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.reflect.Method.invoke(Native Method)
&nbsp; &nbsp; &nbsp; &nbsp; at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
&nbsp; &nbsp; &nbsp; &nbsp; at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devilsen/CZXing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 上午10:04
收件人:&nbsp;"devilsen/CZXing"<CZXing@noreply.github.com&gt;;
抄送:&nbsp;"风儿"<964465281@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [devilsen/CZXing] 生成二维码 (#122)





 
clean一下试试，我看打的包里是有 so 文件的

**Comment by devilsen** [comment]
底层都用的同一个 so 文件的呀，不应该出现这样的情况。

**Comment by 1lyy2** [comment]
我也觉得，我测试二维码扫码可以了，就没多想了，但是调用生成二维码界面就是报这个错，难道是我没加配置文件，但是也不对，如果不全的话，连扫码估计都用不了吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devilsen/CZXing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 上午10:39
收件人:&nbsp;"devilsen/CZXing"<CZXing@noreply.github.com&gt;;
抄送:&nbsp;"风儿"<964465281@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [devilsen/CZXing] 生成二维码 (#122)





 
底层都用的同一个 so 文件的呀，不应该出现这样的情况。

**Comment by 1lyy2** [comment]
麻烦有空帮看下啊，不然两三个APP都要改的了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devilsen/CZXing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 上午10:39
收件人:&nbsp;"devilsen/CZXing"<CZXing@noreply.github.com&gt;;
抄送:&nbsp;"风儿"<964465281@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [devilsen/CZXing] 生成二维码 (#122)





 
底层都用的同一个 so 文件的呀，不应该出现这样的情况。

**Comment by devilsen** [comment]
这个不能放在 x86 里面，你看是不是 so 放错文件夹了
