### ISSUE TITLE
设置是否自动缩放

### ISSUE THREAD

**Issue by DreamZXCreator** [devilsen/CZXing#123]
如何取消或者配置自动缩放功能,最好能设置是否自动缩放或者配置缩放属性?

**Comment by devilsen** [comment]
已添加

**Comment by devilsen** [comment]
enableOpenCVDetect(false)

**Comment by StephenZKCurry** [comment]
使用ScanView自定义界面的方式可以取消OpenCV探测吗

**Comment by devilsen** [comment]
可以通过
BarcodeReader.getInstance().enableCVDetect(false);
直接关闭。
@StephenZKCurry

**Comment by StephenZKCurry** [comment]
@devilsen 感谢
