### ISSUE TITLE
相机初始化失败

### ISSUE THREAD

**Issue by luncang** [devilsen/CZXing#124]
在小米note3，iqoo pro上，进入扫描页面申请相机权限，授权之后，相机初始化失败，提前申请相机权限则可以。
华为荣耀手机，进入扫描页面申请相机权限，授权之后，相机初始化成功

**Comment by devilsen** [comment]
这个问题之前也解决过，但是目前手头上没有这类的手机了。。不太好处理😅

**Comment by devilsen** [comment]
准备升级至 Camera2
