### ISSUE TITLE
请增加拍照功能吧

### ISSUE THREAD

**Issue by LoveToEatGrapes** [devilsen/CZXing#127]

**Comment by devilsen** [comment]
可是，这是一个二维码扫描组件呀😂

**Comment by devilsen** [comment]
其实这里已经拿到相机的数据了，只要找时机保存就好了

**Comment by LoveToEatGrapes** [comment]
我试了试没拿到相机的对象。嗯嗯


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devilsen/CZXing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 上午10:23
收件人:&nbsp;"devilsen/CZXing"<CZXing@noreply.github.com&gt;;
抄送:&nbsp;"房东小孩"<1163574146@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [devilsen/CZXing] 请增加拍照功能吧 (#127)





 
其实这里已经拿到相机的数据了，只要找时机保存就好了

**Comment by LoveToEatGrapes** [comment]
大佬，我觉得可以在自定义布局中&nbsp; == 》 增加扫描针的样式（例如：图片）
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devilsen/CZXing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 上午10:23
收件人:&nbsp;"devilsen/CZXing"<CZXing@noreply.github.com&gt;;
抄送:&nbsp;"房东小孩"<1163574146@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [devilsen/CZXing] 请增加拍照功能吧 (#127)





 
其实这里已经拿到相机的数据了，只要找时机保存就好了

**Comment by devilsen** [comment]
可以参考这个 https://github.com/devilsen/devileye

**Comment by LoveToEatGrapes** [comment]
还是要谢谢lz啊
