### ISSUE TITLE
相机预览放大问题

### ISSUE THREAD

**Issue by StephenZKCurry** [devilsen/CZXing#128]
使用ScanView自定义界面的方式识别二维码，在调用openCamera()方法后（并未调用startScan()开始识别）展示的相机预览画面会拉伸放大，这个效果可以取消吗

**Comment by devilsen** [comment]
提前设置BarcodeReader.getInstance().enableCVDetect(false);就可以了

**Comment by StephenZKCurry** [comment]
> 提前设置BarcodeReader.getInstance().enableCVDetect(false);就可以了

我是在调用openCamera()方法前设置了BarcodeReader.getInstance().enableCVDetect(false)，没有效果
