### ISSUE TITLE
自定义扫码界面问题：

### ISSUE THREAD

**Issue by LoveToEatGrapes** [devilsen/CZXing#129]
1.自定义界面，设置扫码框、背景色、以及四个边角的时候为啥不能设置无色
2.扫描线的渐变高度是否可以自定义

**Comment by devilsen** [comment]
1. 颜色设置时设定 0x00ffffff 就可以了
2. 渐变高度是指啥？

**Comment by LoveToEatGrapes** [comment]
1.解决
2.类似于支付宝的那种扫描样式，或者可以设置扫描针为图片是这个意思

**Comment by devilsen** [comment]
目前这种样式不是都要被淘汰了吗😂给你们设计提意见，就不改了吧

**Comment by LoveToEatGrapes** [comment]
哈哈哈，好的，要淘汰了啊？好吧
