### ISSUE TITLE
扫描时会频繁的放大

### ISSUE THREAD

**Issue by FynnJason** [devilsen/CZXing#13]
使用0.6APK，在测试扫描时，还没对准二维码，就开始放大，而且不是放大一次，是持续的放大，经过多次测试，发现不管对准键盘，还是对准电脑屏幕，也不管屏幕里面是否存在二维码，反正就是会放大，而且确实是多次放大，不断的去放大。不过二维码识别还可以，支持

**Comment by devilsen** [comment]
这也是图像识别处理的短板，生活中我们可以直接对物品做出判断，但是用一张图让手机识别还是有难度的，在文章中也有图像识别的逻辑介绍，相交微信来说这个识别率并不高，而区别也在与此，如果要防止过度的放大，只能把图像过滤的阈值调大，但是这对于远距离的识别来说又削减了太多，现在也只是一个折中的方案，如果之后能训练出好的机器学习case，这个问题才能比较好的解决。

**Comment by FynnJason** [comment]
那理论上来说，尽量是优先保证识别率和速率，因为在生活中，大多数人扫码都不会距离太远，相对于很多中年人和老年人，他们扫码的时候，反而会距离非常近，恨不得把手机贴在二维码上，这是观察生活得出来的，所以我觉得识别效率还是最优先级的，宁可让用户自己把手机贴近点二维码，因为对于他们来说，并不厌烦这么做

**Comment by devilsen** [comment]
其实在我的测试中，大部分机型的识别效率还是很高的，只是一些手机的摄像头素质不高，在放大之后获取的图像质量不高导致的（华为的荣耀系列比较严重），这些问题还得针对机型慢慢优化。
