### ISSUE TITLE
crash when repeated recognition

### ISSUE THREAD

**Issue by ffyliu** [devilsen/CZXing#131]
hi
   Process: Enter QR code recognition and then recognize the successful jump
   Repeat the above operation several times, and it will crash 
   
   device：android Q，huawei mate 30 pro

[tombstone_08.txt](https://github.com/devilsen/CZXing/files/5266447/tombstone_08.txt)

**Comment by devilsen** [comment]
I see the logs, but I don't think it's the lib error, libjavacrypto.so seems more suspicious.

**Comment by kwg520** [comment]
扫到就成功，打开扫码界面一会就蹦了

**Comment by kwg520** [comment]
在没二维码扫的情况下

**Comment by devilsen** [comment]
这个都是测试过的呀😂进群聊吧 QQ Group ID:287113918
