### ISSUE TITLE
如何设置解码的编码方式

### ISSUE THREAD

**Issue by easywangzhe** [devilsen/CZXing#14]
由于二维码的编码格式问题,导致解析后中文乱码,
这边没有对外暴露ZXING的DecodeHintType.CHARACTER_SET的字符编码格式方法吗?

**Comment by devilsen** [comment]
我没太理解你的意思，是中文被编码了吗？如果是文字被编码，直接把识别出来的文字反编码不是可以吗？二维码也只是容器。
