### ISSUE TITLE
有考虑引入wechat_qrcode模块吗？

### ISSUE THREAD

**Issue by DyncKathline** [devilsen/CZXing#146]
最新的opencv_contrib加入了wechat_qrcode模块，我进行了编译，按照这篇博客https://blog.csdn.net/poorkick/article/details/113665108 ，识别率和识别速度大大提高了，但是目前不知道怎么抽离出来，请问你能集成进去吗

**Comment by tanranran** [comment]
万众求增

**Comment by devilsen** [comment]
用的应该是一套东西，我研究下

**Comment by asdzheng** [comment]
看到有人已经把库弄出来了，也是跟opencv结合，强烈求整合到czxing
https://github.com/onlyloveyd/WeChatQRCode

**Comment by devilsen** [comment]
@asdzheng 正在引入，不过OpenCV编译起来比较反人类

**Comment by asdzheng** [comment]
辛苦大佬
