### ISSUE TITLE
使用ScanView来自定义界面时，界面黑屏，没有显示相机视野

### ISSUE THREAD

**Issue by Sindyue** [devilsen/CZXing#17]
使用ScanView来自定义界面时，界面黑屏，没有显示相机视野，也无法进行扫描

**Comment by yuanshenzhen** [comment]
同样问题，机型Vivo IQOO

**Comment by devilsen** [comment]
这个问题一般是没有相机权限，在0.6中加入了打开页面时自动申请，或者自己在主界面申请，都可以试下。
