### ISSUE TITLE
识别速率问题

### ISSUE THREAD

**Issue by mzhs-git** [devilsen/CZXing#20]
1.放大问题，放大有点着急，用户还没有对准二维码的时候就放大了，而且放大后的二维码大于扫描框，微信放大若干次后，二维码也不会大于扫描框，这时候用户会拉后手机位置
2.对于透视的码识别率很低，像上下左右倾斜，左上坐下，右上右下，实际生产环境中，码可能在不同的位置，这时候如果不上前对正还能识别，那就太赞了，微信在这方面做的很不错
3.对面有光时识别不了，这个开源框架大部分都没有解决这个问题
这段时间正在为货架二维码识别速率低的问题发愁，提出的问题可能不切实际，还请见谅

**Comment by devilsen** [comment]
1. 大家的问题都集中在放大上，这个会集中修改。
2. 对于特殊的二维码可以提供图片，我会调整参数，尝试与微信的识别靠齐。
3. 货架二维码是什么样的呢？没有具体的概念，如果可以的话也可以提供实际的图片，如果想研究的话，你可以专门去做这方面的处理，比如[颜色过滤](https://blog.csdn.net/jianjian1992/article/details/51274834)

**Comment by mzhs-git** [comment]
> 1. 大家的问题都集中在放大上，这个会集中修改。
> 2. 对于特殊的二维码可以提供图片，我会调整参数，尝试与微信的识别靠齐。
> 3. 货架二维码是什么样的呢？没有具体的概念，如果可以的话也可以提供实际的图片，如果想研究的话，你可以专门去做这方面的处理，比如[颜色过滤](https://blog.csdn.net/jianjian1992/article/details/51274834)

2.第二点中的二维码就是手机和二维码没有对正，手机可能在二维码的左上方扫描
3.货架二维码是我们把货架编了个号，每个货架格子有个二维码，所以经常会很难对正，因为有的格子高有的低
下面两张图可以参考下
![WeChat Image_20190807140442](https://user-images.githubusercontent.com/7136014/62598606-813d1e80-b91c-11e9-9137-910de2075fd0.jpg)
![WeChat Image_20190807140501](https://user-images.githubusercontent.com/7136014/62598613-8601d280-b91c-11e9-88a9-07f5397fbb8c.jpg)

**Comment by mzhs-git** [comment]
两个图片目标都是为了扫H9，微信都可以扫描出来，而且速度可以接受，你试着用demoapp扫下，第二个可能能扫出来，但是速度很慢，第一个我没扫出来过。生活中这个是很常见的需求，用户不懂这个，不会对正，所以如果各个角度的二维码都可以认识的话，就方便多了。

**Comment by devilsen** [comment]
优化了一版，效果虽然还比不上微信，不过可以先试下，我这边可以顺利扫出第二个。

**Comment by mzhs-git** [comment]
> 优化了一版，效果虽然还比不上微信，不过可以先试下，我这边可以顺利扫出第二个。

谢谢大神做的努力，我这边下载下demo试试，我觉得得在变型码校正代码上下功夫，处理逆光，高光部分过多的问题其实没有那么重要。

**Comment by maybelife** [comment]
相比于zxing ,zbar对于倾斜角度的二维码，还有变形的二维码 ，基本都能识别出来

**Comment by maybelife** [comment]
第一张图H9的二维码，第二章图H9 R10, 用zbar 都可以识别出来
其他的 zbar识别不出来，用微信也识别不出来，意见可以参考下zbar的

**Comment by devilsen** [comment]
@maybelife 我去看下zbar的逻辑，感觉又是一个坑😂。。

**Comment by devilsen** [comment]
已优化
