### ISSUE TITLE
识别不出来

### ISSUE THREAD

**Issue by 54binge** [devilsen/CZXing#21]
这个是我司的一个设备的二维码，印刷是有点问题，不清晰，但是使用微信和我查查都能秒扫出来，这个库一次没有扫出来
![image](https://user-images.githubusercontent.com/4814206/62523681-e9c9c400-b866-11e9-9de2-ea469ae3c1bd.png)

**Comment by devilsen** [comment]
确实没测试过这样的，我看下😀

**Comment by caobin821651400** [comment]
这个以前遇到过，有些设备上的二维码很难扫，你这个需要斜45°就很快扫出来。

**Comment by devilsen** [comment]
测试了两晚上，发现这个是真的有难度，最后用微信测试，在我这个旧手机上微信也扫不出来_(:з」∠)_，明天试下其他手机吧。。。

**Comment by 54binge** [comment]
这样的二维码确实很难扫，但是用微信我这边也是秒扫，离一尺左右最快，太大反而慢了一点

**Comment by 54binge** [comment]
还发现个问题，微信扫描放大最大为扫码框大小就不会自动放大了，这个库放大会超出扫码框，应该是没识别出二维码

**Comment by devilsen** [comment]
加入了zbar，现在能扫出来了，但是效率还不高。
