### ISSUE TITLE
这个二维码识别不出来

### ISSUE THREAD

**Issue by okayFan** [devilsen/CZXing#26]
![image](https://user-images.githubusercontent.com/20924164/62688980-807bb980-b9fc-11e9-8b7f-df88c5ff7e13.png)
为什么这个二维码Demo的app识别不出来呢

**Comment by devilsen** [comment]
#20 应该都是识别角度的问题，最近研究一下这个。

**Comment by cike978** [comment]
微信也识别不出来，估计二维码有问题

**Comment by devilsen** [comment]
加入了zbar的识别，相较之前好了很多。
