### ISSUE TITLE
请问大佬这个二维码为什么识别不了呢？

### ISSUE THREAD

**Issue by okayFan** [devilsen/CZXing#28]
![image](https://user-images.githubusercontent.com/20924164/62764156-cbaad080-babf-11e9-8629-17600fa35ce7.png)

**Comment by devilsen** [comment]
其实你在用微信扫描这个的时候，会发现离的比较远的情况下是比近的时候识别的快的，应该是纠错码的等级太低，造成图片识别的时候总是出现错误，可以尝试一些其他的生成方式，多用几张二维码试试。

**Comment by okayFan** [comment]
大佬，为啥咱们这个二维码框架识别不了这个二维码呢...是这个二维码生成有问题的原因么？

**Comment by devilsen** [comment]
> 大佬，为啥咱们这个二维码框架识别不了这个二维码呢...是这个二维码生成有问题的原因么？

应该是的，二维码生成也是有一定规则的，如果纠错码的级别太低，是会影响到识别的准确度的，而且你的二维码中间还有图标，是要把纠错码的等级提的高一些的，你可以试试在网站上生成一个带图标的二维码，应该要比这个识别的快。
