### ISSUE TITLE
求解 相册 相册识别二维码一直走失败逻辑

### ISSUE THREAD

**Issue by jhbxyz** [devilsen/CZXing#29]
无论这个图片上的二维码多清晰,还是识别不出来,谢谢!

**Comment by devilsen** [comment]
这块确实有一些很异样的问题，最近在尝试下沉线程的处理，可能要过一段时间处理。

**Comment by jhbxyz** [comment]
> 这块确实有一些很异样的问题，最近在尝试下沉线程的处理，可能要过一段时间处理。

大佬 新项目想用这个库 这个相册识别能尽快搞好吗 扫描是没问题的 挺快的  就差这个相册识别了

**Comment by devilsen** [comment]
@jhbxyz 我试了下，效果还可以呀，你检查一下选择图片时候返回的路径能不能对的上。

**Comment by jhbxyz** [comment]
> @jhbxyz 我试了下，效果还可以呀，你检查一下选择图片时候返回的路径能不能对的上。

我跑了下你的 Demo 选择相册是有问题的 第一次可以 之后闪退,希望相册这方面能优化下

**Comment by devilsen** [comment]
麻烦贴一下log和手机版本
