### ISSUE TITLE
打开相机界面闪退

### ISSUE THREAD

**Issue by ggggskd** [devilsen/CZXing#30]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/cepheus/cepheus:9/PKQ1.181121.001/9.7.22:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 13510, tid: 13887, name: decode dispatch  >>> com.kbz.czxing <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: use of invalid jobject 0x438'
    r0  00000000  r1  0000363f  r2  00000006  r3  00000008
    r4  000034c6  r5  0000363f  r6  d06257bc  r7  0000010c
    r8  00000000  r9  f281c740  r10 f3717d2c  r11 f21a3cee
    ip  f5f843cc  sp  d06257a8  lr  f5eef7d9  pc  f5ee6ffe

backtrace:
    #00 pc 0001cffe  /system/lib/libc.so (abort+58)
    #01 pc 0034e97b  /system/lib/libart.so (art::Runtime::Abort(char const*)+910)
    #02 pc 0000738f  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+494)
    #03 pc 00232b53  /system/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1214)
    #04 pc 00232d1f  /system/lib/libart.so (art::JavaVMExt::JniAbortF(char const*, char const*, ...)+66)
    #05 pc 003742ed  /system/lib/libart.so (art::Thread::DecodeJObject(_jobject*) const+568)
    #06 pc 002984db  /system/lib/libart.so (art::JNI::SetObjectArrayElement(_JNIEnv*, _jobjectArray*, int, _jobject*)+406)
    #07 pc 0009f425  /data/data/com.kbz.czxing/files/library/libczxing.so
    #08 pc 0000042d  /data/data/com.kbz.czxing/files/oat/arm/a.odex (offset 0x4000)

**Comment by devilsen** [comment]
加入abiFilter试试
