### ISSUE TITLE
相册选取图片识别问题

### ISSUE THREAD

**Issue by youweiHe** [devilsen/CZXing#32]
大佬，不知道是不是我用的姿势不对，
“点击扫码"->"调起相机扫码"->”点击右上角相册选取二维码图片"【正常操作没问题，但是如果选取照片的时候，相机正好也对着二维码的话， 会先识别相机下的二维码并回调处理，然后按返回键后又会回到选择图片页】
感谢大佬提供，大佬辛苦

**Comment by devilsen** [comment]
是要不识别二维码吗？还是不打开相册？理论上你可以自己控制，这里为了演示用的是系统相册，你可以使用一些三方的图片选择控件，自己控制Activity的逻辑。
