### ISSUE TITLE
如何设置：只识别扫描框里的二维码，如果二维码不在扫描框内则不去识别

### ISSUE THREAD

**Issue by zhangwenxiang26** [devilsen/CZXing#33]

**Comment by zhangwenxiang26** [comment]
@devilsen

**Comment by zhangwenxiang26** [comment]
![image](https://user-images.githubusercontent.com/19923561/63260670-26101200-c2b4-11e9-8a2b-341865f143e9.png)

**Comment by devilsen** [comment]
现在默认是只识别扫描框里的数据，不过为了增加扫码范围，会处理几帧与屏幕宽的界面，如果有这样 的需求可以增加一个这样的API。

**Comment by zhangwenxiang26** [comment]
你好，你这个库，识别效率确实很高。我想把它用在项目上，针对上面问题，我应该从哪一块入手，去实现这个功能呢？

**Comment by zhangwenxiang26** [comment]
@devilsen

**Comment by devilsen** [comment]
确实有你说的这样的需求，晚上回去加一下。

**Comment by zhangwenxiang26** [comment]
> 确实有你说的这样的需求，晚上回去加一下。

我发现这样修改代码能实现，只识别扫描框中二维码，但是不知道会有什么影响？

BarCoderView  类

源代码

if (scanSequence < 5) {
          onPreviewFrame(data, left, top, scanBoxSize, scanBoxSize, rowWidth, rowHeight);
   } else {
          scanSequence = -1;
          int bisSize = rowWidth < rowHeight ? rowWidth : rowHeight;
          onPreviewFrame(data, 0, top, bisSize, bisSize, rowWidth, rowHeight);
   }
          scanSequence++;

修改如下

onPreviewFrame(data, left, top, scanBoxSize, scanBoxSize, rowWidth, rowHeight);

//   if (scanSequence < 5) {
//          onPreviewFrame(data, left, top, scanBoxSize, scanBoxSize, rowWidth, rowHeight);
//     } else {
//          scanSequence = -1;
//          int bisSize = rowWidth < rowHeight ? rowWidth : rowHeight;
//          onPreviewFrame(data, 0, top, bisSize, bisSize, rowWidth, rowHeight);
//     }
 //         scanSequence++;

@devilsen   这样修改会有什么问题码？

**Comment by devilsen** [comment]
没问题，就是在这里修改的。

**Comment by devilsen** [comment]
已加入api  setScanMode(ScanView.SCAN_MODE_TINY)
