### ISSUE TITLE
onScanSuccess 里执行UI操作，不报错，但会导致ANR

### ISSUE THREAD

**Issue by lhhseraph** [devilsen/CZXing#38]
onScanSuccess 里执行UI操作，不报错，但会导致ANR，里面另起UI线程执行UI操作则没问题

 

 
   @Override
    public void onScanSuccess(final String result) {
        Log.e("onScanSuccess", result);
        mSoundPoolUtil.play();
        mScanView.stopScan();

       //不报错，不弹框，执行这个后，按返回  ANR
        new AlertDialog.Builder(ScanActivity.this).setTitle("最新通知").setMessage(result)
                .setCancelable(true).setOnDismissListener(new DialogInterface.OnDismissListener() {
            @Override
            public void onDismiss(DialogInterface dialogInterface) {
                mScanView.startScan(); // 显示扫描框，并开始识别
            }
        }).show();

       //不报错，弹框，执行这个后，按返回  正常
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                new AlertDialog.Builder(ScanActivity.this).setTitle("最新通知").setMessage(result)
                        .setCancelable(true).setOnDismissListener(new DialogInterface.OnDismissListener() {
                    @Override
                    public void onDismiss(DialogInterface dialogInterface) {
                        mScanView.startScan(); // 显示扫描框，并开始识别
                    }
                }).show();
            }
        });
}

**Comment by devilsen** [comment]
其实我觉得这样没啥问题，在子线程返回的话有更大的操作空间，可以操作自己需要处理的耗时任务，而且转到主线程的话我的操作和你的也差不多。
