### ISSUE TITLE
BarcodeReader 这个对象被回收时候必崩溃

### ISSUE THREAD

**Issue by ltxjxqy3** [devilsen/CZXing#39]
比如我在activity里面创建这个对象，然后activity destroy之后，BarcodeReader这个对象被回收，会自己调用finalize 方法，然后NativeSdk.getInstance().destroyInstance(_nativePtr);
这边必崩溃
我把BarcodeReader 创建出来的对象改为static  就没问题了

还有一个问题，我看到有人已经提过，就是打开扫码页，退出后再马上进入，测试的小米4.4.4的手机会黑屏，如果等个10秒再进入，就不会黑屏

**Comment by ltxjxqy3** [comment]
08-29 10:53:04.627 15995-15995/me.devilsen.czxing E/onOpenCameraError: onOpenCameraError
08-29 10:53:04.627 15995-15995/me.devilsen.czxing W/CameraBase: An error occurred while connecting to camera: 0
08-29 10:53:04.627 15995-15995/me.devilsen.czxing W/System.err: java.lang.RuntimeException: Fail to connect to camera service
08-29 10:53:04.627 15995-15995/me.devilsen.czxing W/System.err:     at android.hardware.Camera.native_setup(Native Method)
08-29 10:53:04.627 15995-15995/me.devilsen.czxing W/System.err:     at android.hardware.Camera.<init>(Camera.java:396)
08-29 10:53:04.627 15995-15995/me.devilsen.czxing W/System.err:     at android.hardware.Camera.open(Camera.java:351)
08-29 10:53:04.627 15995-15995/me.devilsen.czxing W/System.err:     at me.devilsen.czxing.view.BarCoderView.startCameraById(BarCoderView.java:192)
08-29 10:53:04.637 15995-15995/me.devilsen.czxing W/System.err:     at me.devilsen.czxing.view.BarCoderView.openCamera(BarCoderView.java:160)
08-29 10:53:04.637 15995-15995/me.devilsen.czxing W/System.err:     at me.devilsen.czxing.view.ScanView.openCamera(ScanView.java:23)
08-29 10:53:04.637 15995-15995/me.devilsen.czxing W/System.err:     at me.devilsen.czxing.view.BarCoderView.openCamera(BarCoderView.java:151)
08-29 10:53:04.637 15995-15995/me.devilsen.czxing W/System.err:     at me.devilsen.czxing.view.ScanView.openCamera(ScanView.java:23)
08-29 10:53:04.637 15995-15995/me.devilsen.czxing W/System.err:     at me.devilsen.czxing.view.BarCoderView.startScan(BarCoderView.java:133)
08-29 10:53:04.637 15995-15995/me.devilsen.czxing W/System.err:     at me.devilsen.czxing.view.ScanView.startScan(ScanView.java:65)
08-29 10:53:04.637 15995-15995/me.devilsen.czxing W/System.err:     at me.devilsen.czxing.ScanActivity.onStart(ScanActivity.java:85)

**Comment by ltxjxqy3** [comment]
初步排查，低版本手机连续开关扫码页面，会出现黑屏的现象是由于ScanActivity的onStop和onDestroy延迟执行造成，  所以退出扫码页并又快速进入的时候，onResume里面初始化摄像头，由于Camera未被释放，所以黑屏，高版本手机试了下，可以允许两个应用同时开启Camera，所以高版本手机不会有问题
初步解决方案可以在ScanActivity 的finish回收camera
@Override
    public void finish() {
        super.finish();
        mScanView.stopScan();
        mScanView.closeCamera(); // 关闭摄像头预览，并且隐藏扫描框

        mScanView.onDestroy(); // 销毁二维码扫描控件
        mSoundPoolUtil.release();
    }

**Comment by devilsen** [comment]
感谢反馈，已修复。
