### ISSUE TITLE
libczxing.so库忘记提交了

### ISSUE THREAD

**Issue by xiangdada** [devilsen/CZXing#41]
`implementation project(':czxing')`
打包时会报找不到libczxing.so，
`implementation 'me.devilsen:CZXing:0.8.3'`
则不会报找不到库错误

看了libs目录下确实没有找到这个库

**Comment by xiangdada** [comment]
记错了，是运行时报找不到这个so

**Comment by devilsen** [comment]
这个是自动生成的呀，如果你有NDK环境会自动生成，如果你找不到的话，可以找到czxing的aar，（在.gradle/caches/modules-2/files-2.1/me.devilsen/ ）拿到里面的so文件，但是也要自己搭建好环境。
我考虑下以后也上传.so文件，方便没有NDK环境的同学开发。
