### ISSUE TITLE
红米note 8pro打不开闪光灯

### ISSUE THREAD

**Issue by fancaicai** [devilsen/CZXing#42]
我的红米note 8pro打不开闪光灯的时候没反应，希望作者能够帮忙解决一下下哦！

**Comment by devilsen** [comment]
因为这边没有找到红米note8，我在小米6、8以及红米K20上测试都没有问题，是不是那个点击区域太小没有点到呢？这几天也优化了一些闪光灯的体验，你可以再试下。
