### ISSUE TITLE
在扫码页申请权限有问题，

### ISSUE THREAD

**Issue by ltxjxqy3** [devilsen/CZXing#44]
大佬，又发现你一个bug，就是在ScanActivity这个页面内申请权限，然后扫码就会有问题，导致一直扫一直扫，但是没有结果
原因是因为在这边BarCoderView这个类里面
private void startCameraById(int cameraId) {
        try {
            mCameraId = cameraId;
            mCamera = Camera.open(cameraId);
            mCameraSurface.setCamera(mCamera);
        } catch (Exception e) {
            e.printStackTrace();
            if (mScanListener != null) {
                mScanListener.onOpenCameraError();
            }
        }
    }
如果没有权限的话  Camera.open就会异常，然后 mCameraSurface.setCamera(mCamera) 不会去执行，导致setCamera这个方法里面getHolder().addCallback(this)  不会去执行，虽然申请完权限以后，这边能执行到，但是时机不对了，surfaceCreated这个不会回调，里面的mSurfaceCreated就永远为false

**Comment by devilsen** [comment]
感谢反馈，已修复。

**Comment by iyezhou** [comment]
@devilsen 怎么解决的，貌似还是有这个问题
