### ISSUE TITLE
横屏会崩溃，二维码没在扫码的那个正方形内，但是在屏幕上也能扫成功

### ISSUE THREAD

**Issue by liu0124** [devilsen/CZXing#46]
横屏会崩溃，二维码没在扫码的那个正方形内，是在屏幕上扫码框正方形外也能扫成功

**Comment by devilsen** [comment]
感谢反馈，崩溃问题已修复。
如果只想扫描扫码框里的内容，可以配置参数  .setScanMode(ScanView.SCAN_MODE_TINY)
