### ISSUE TITLE
建议调整缩放策略

### ISSUE THREAD

**Issue by leeyun** [devilsen/CZXing#49]
现在会出现一个很尴尬的情况对准任意位置都会一直放大镜头这样有点不太好吧。

**Comment by devilsen** [comment]
#49

**Comment by hb0800417** [comment]
对比了下微信的，，他们好像只有扫描条码和二维码 距离过远的时候 或者光线不好的时候放大。这个只要扫描到文字就开始放大了

**Comment by hb0800417** [comment]
看了下源码，也进行了测试 你是通过tryZoom方法内的result.getPoints().length() 获取点的数量。然后判断。。通过测试，扫描了文字和复杂二维码放大时取到的点数，都是6.无法区分文字和二维码

**Comment by devilsen** [comment]
> 看了下源码，也进行了测试 你是通过tryZoom方法内的result.getPoints().length() 获取点的数量。然后判断。。通过测试，扫描了文字和复杂二维码放大时取到的点数，都是6.无法区分文字和二维码

主要是OpenCv处理图像的阈值比较低，造成识别其他物件也会认为是二维码，目前在解决这个问题。
