### ISSUE TITLE
频繁快速进出ScanActivity 个别手机会出现崩溃

### ISSUE THREAD

**Issue by lhhseraph** [devilsen/CZXing#54]
[Uploading 频繁进出扫描界面几次崩溃.txt…]()
在demo中ScanActivity基础上添加了扫码后的业务逻辑。当频繁调用ScanActivity（期间不做任何扫描）后快速退出，几次后就会崩溃。错误信息看不太懂，就贴上完整的
Invalid address 0xfff8c818 passed to free: value not allocated

0.8.9 及以前的版本没问题，0.9开始的版本出现该问题

**Comment by devilsen** [comment]
日志好像没传上来

**Comment by lhhseraph** [comment]
[频繁进出扫描界面几次崩溃.txt](https://github.com/devilsen/CZXing/files/3633754/default.txt)


> 日志好像没传上来

**Comment by devilsen** [comment]
已修复

**Comment by lhhseraph** [comment]
> 已修复

谢谢，测试发现偶尔还是会，但 不容易重现了，不知道是不是主页几个动画播放和手机内存小的原因
