### ISSUE TITLE
感觉很奇怪啊，打的二维码离的近了扫不出来，离得远了反而能扫出来

### ISSUE THREAD

**Issue by 643063150** [devilsen/CZXing#55]
![{42A3C800-73D6-B1D3-34E6-CDADED7DE1DC}](https://user-images.githubusercontent.com/11732536/65311867-f1012300-dbc3-11e9-9c1a-90d0ccb65e0c.jpg)
这个码，在pc上打开大图扫描离得近死活扫不出来，离得远点马上就能扫出来，在手机qq上特别小的图也能扫出来，这个扫除不出来就疯狂放大 建议优化一下

**Comment by devilsen** [comment]
我测试没问题的呀

**Comment by 643063150** [comment]
这张图哎qq聊天窗打开大图，让二维码刚好在扫描框里且基本一样大，就会马上放大，然后一直放大扫不出来

**Comment by devilsen** [comment]
优化了扫码策略，应该好一点了
