### ISSUE TITLE
Vivo x9手机上生成二维码报错

### ISSUE THREAD

**Issue by AymerZhang** [devilsen/CZXing#58]
最终报错的语句应该是JNIUtils.cpp下的ANSIToUnicode()函数的len = std::mbsrtowcs(buff.get(), &src, len, &state);这一行代码。

搜索了一下相关的内容，但是不是很了解C++并没有解决问题 以下是报错信息。

CrashReport: SIGSEGV(SEGV_MAPERR)
    0x0
    #00    pc 0000000000029070    /system/lib64/libc.so (mbsnrtowcs+116) [arm64-v8a::6a062cc4089937243c9c9e1479435085]
    #01    pc 00000000000fbe5c    /data/app/com.chehejia.oc.m01-2/lib/arm64/libczxing.so (_Z13ANSIToUnicodeRKNSt6__ndk112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE+208) [arm64-v8a::181f0c632f261337a425a6e1902e4b8d]
    #02    pc 00000000000f2834    /data/app/com.chehejia.oc.m01-2/lib/arm64/libczxing.so (Java_me_devilsen_czxing_BarcodeWriter_writeCode+136) [arm64-v8a::181f0c632f261337a425a6e1902e4b8d]
    #03    pc 0000000001f23738    /data/app/com.chehejia.oc.m01-2/oat/arm64/base.odex (oatexec+894776) [arm64-v8a::6d1b0000000000000000000000000000]
    java:
    me.devilsen.czxing.BarcodeWriter.write(BarcodeWriter.java:102)
    me.devilsen.czxing.BarcodeWriter.write(BarcodeWriter.java:49)
    com.chehejia.oc.m01.view.gui.user.usercenter.MyQrCodeActivity$2.onResourceReady(MyQrCodeActivity.java:97)
    com.chehejia.oc.m01.view.gui.user.usercenter.MyQrCodeActivity$2.onResourceReady(MyQrCodeActivity.java:94)
    com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:582)
    com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:544)
    com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:152)
    com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:398)
    android.os.Handler.handleCallback(Handler.java:751)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6211)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)

**Comment by devilsen** [comment]
终于找到了一台Vivo X9的手机，但是我测试没有复现问题呀
