### ISSUE TITLE
希望自定义界面能更加灵活点。

### ISSUE THREAD

**Issue by pigff** [devilsen/CZXing#59]
hi，我觉得这个扫码功能做的真很好，无论是速率还是识别率我都觉得很牛逼。
但是我发现里面应该是没有相应的接口或者参数配置提供是否隐藏扫码框下方的提示文字和设置扫码框所在的位置。
所以我希望能提供这些方法，或者直接在xml里就能够配置。

<img width="271" alt="img" src="https://user-images.githubusercontent.com/23067774/65477703-b942f580-deb9-11e9-8331-36042857a929.png">

就是像图上这样

**Comment by devilsen** [comment]
目前还是在解决底层的一些问题，暂时没有精力做太复杂的API引入，不过你可以通过ScanView自定义你的界面，我可以提供一些简单的api，比如隐藏提示文字，或者更改文字颜色，帮助你完成界面。

**Comment by pigff** [comment]
嗯嗯。 多谢。

**Comment by devilsen** [comment]
已添加api
