### ISSUE TITLE
之前的问题是横屏闪退，现在的问题是竖屏识别不了，横屏能识别

### ISSUE THREAD

**Issue by liu0124** [devilsen/CZXing#62]
加油

**Comment by liu0124** [comment]
还一个问题是打开工程ERROR: This version of Android Studio cannot open this project, please retry with Android Studio 3.5 or newer

**Comment by devilsen** [comment]
不会呀……我一直用的竖屏测试，是不是某款手机或者不小心触发某个条件时出现的。
第二个问题肯定是升级就好了，3.5的编译比之前快了好多。

**Comment by liu0124** [comment]
今天竖屏扫码又可以了，感觉好奇怪，但是生成不了二维码，闪退public void onScanResult(String s, BarcodeFormat barcodeFormat) {
                                BarcodeWriter writer = new BarcodeWriter();
                                Bitmap bitmap = writer.write(s, BarCodeUtil.dp2px(MainActivity.this, 200),Color.BLACK, null);
                                iv.setImageBitmap(bitmap);
                            }

**Comment by devilsen** [comment]
@liu0124 有没有具体的crash日志呢？
