### ISSUE TITLE
识别框大小问题

### ISSUE THREAD

**Issue by Wxianpeng** [devilsen/CZXing#64]
是否支持自定义识别框大小？

**Comment by zhangwenxiang26** [comment]
找到  ScanBoxView  这个类 ---------》 找的这个方法 calFramingRect()  可以自定义扫描框大小以及位置
@Wxianpeng    ；只能希望大佬以后有时间，把自定义属性加上，现在只能拿到jar包自己改了

**Comment by devilsen** [comment]
已优化
