### ISSUE TITLE
simple会挂掉

### ISSUE THREAD

**Issue by huangchengzuo** [devilsen/CZXing#68]
扫描 后继续对着二维码 稍微动一动 就会自动对焦  感觉还会增加曝光一样 预览图会变得比较白然后就挂了 
 Fatal signal 11 (SIGSEGV), code 0, fault addr 0x4f69 in tid 20688 (Thread-2361)
没按到什么error信息 ，只有这个
实在一个摩托摩拉手机上 型号DROID TURBO    Android6.01 版本

**Comment by huangchengzuo** [comment]
10-25 18:14:25.931 23012-23012/me.devilsen.czxing D/CZXing >>>: 缩小
10-25 18:14:25.953 23012-23012/me.devilsen.czxing D/CZXing >>>: 缩小
10-25 18:14:25.991 23012-23012/me.devilsen.czxing D/CZXing >>>: 缩小
10-25 18:14:26.022 23012-23012/me.devilsen.czxing D/CZXing >>>: 缩小
10-25 18:14:26.275 23012-23523/me.devilsen.czxing D/CrashReport-Native: Finished waiting 1031 ms.
10-25 18:14:26.275 23012-23523/me.devilsen.czxing I/CrashReport-Native: Failed to handle this native crash in Java profile.
10-25 18:14:26.275 23012-23523/me.devilsen.czxing I/CrashReport-Native: Record Java stack.
10-25 18:14:26.275 23012-23523/me.devilsen.czxing I/CrashReport-Native: Java stack has been recorded.
10-25 18:14:26.275 23012-23523/me.devilsen.czxing I/CrashReport-Native: Clear eupInfo object.
10-25 18:14:26.275 23012-23523/me.devilsen.czxing I/CrashReport-Native: Try to unlock file: /data/user/0/me.devilsen.czxing/app_bugly/../files/native_record_lock
10-25 18:14:26.275 23012-23523/me.devilsen.czxing I/CrashReport-Native: Successfully unlock file: /data/user/0/me.devilsen.czxing/app_bugly/../files/native_record_lock
10-25 18:14:26.275 23012-23523/me.devilsen.czxing D/CrashReport-Native: Restored signal handlers.
10-25 18:14:26.275 23012-23523/me.devilsen.czxing D/CrashReport-Native: Unregister signal handlers.
10-25 18:14:26.275 23012-23523/me.devilsen.czxing D/CrashReport-Native: Re-sending signal 'SIGSEGV' to thread: 23523
    
    --------- beginning of crash
10-25 18:14:26.276 23012-23523/me.devilsen.czxing A/libc: Fatal signal 11 (SIGSEGV), code 0, fault addr 0x59e4 in tid 23523 (Thread-2402)
10-25 18:14:27.756 23012-23548/me.devilsen.czxing D/CrashReport: [Upload] Bugly version from headers is: bugly/1.0
10-25 18:14:27.756 23012-23548/me.devilsen.czxing D/CrashReport: [Upload] Status from server is 0 (pid=23012 | tid=23548).
10-25 18:14:27.756 23012-23548/me.devilsen.czxing D/CrashReport: [Upload] Received 145 bytes

**Comment by devilsen** [comment]
试试新的呢，实在是没找到这个型号的手机。。
