### ISSUE TITLE
真实测试模糊的二维码识别率会下降

### ISSUE THREAD

**Issue by HoneyWorld** [devilsen/CZXing#71]
![IMG_20191026_083536](https://user-images.githubusercontent.com/13584168/67650458-fa766b80-f977-11e9-8756-4f9d86022193.jpg)
![IMG_20191026_092539](https://user-images.githubusercontent.com/13584168/67650459-fa766b80-f977-11e9-9c3d-86b720b3d6b2.jpg)
![IMG_20191026_083529](https://user-images.githubusercontent.com/13584168/67650460-fa766b80-f977-11e9-8918-72d37b330f24.jpg)
![IMG_20191026_083533_1](https://user-images.githubusercontent.com/13584168/67650462-fb0f0200-f977-11e9-9b72-33ac9bee56d0.jpg)

**Comment by devilsen** [comment]
已优化
