### ISSUE TITLE
二维码无法识别

### ISSUE THREAD

**Issue by josephyuen** [devilsen/CZXing#75]
https://user-images.githubusercontent.com/20924164/62764186-debda080-babf-11e9-879d-b65dbb5a09a3.png

在别处碰到了一个二维码识别不出，微信和支付宝都可以扫出来，包括Google Lens 也可以。https://github.com/jenly1314/ZXingLite/issues/52    请问大佬如何处理。

**Comment by KnIfER** [comment]
是不是角度不好，这张照片左侧扫有时会识别出来。
