### ISSUE TITLE
二维码内含数据多，太密集的情况下，扫描不出来

### ISSUE THREAD

**Issue by liuleshuai** [devilsen/CZXing#76]
0.9.7新版试用了一下，发现扫描数据多显示密集的二维码扫描不出来，然后手动放大继续扫描该二维码会崩溃

**Comment by devilsen** [comment]
正在修复崩溃的问题

**Comment by liuleshuai** [comment]
还有个想问的问题，CZxing的聚焦是定时触发的，能不能设置成想微信或者UC里面的二维码扫描，能够自适应的聚焦，这一块有扩展的计划嘛？ @devilsen

**Comment by devilsen** [comment]
现在的聚焦支持几种
1. 手动点击聚焦 
2. 传感器聚焦
3. 如果超过指定次数识别失败，自动聚焦

现在的聚焦方式在测试中表现都还不错，你可以打开log具体看下聚焦的问题。

**Comment by liuleshuai** [comment]
当前的聚焦支持不能满足我的需求呀，扫描静止不动，画面会定时的收缩抖动，这是聚焦产生的问题，需求参考的是UC浏览器的二维码扫描，想不到实现方式。。。

**Comment by devilsen** [comment]
加群聊吧，QQ群：287113918
