### ISSUE TITLE
大神，识别不出来的二维码。

### ISSUE THREAD

**Issue by kuaitao** [devilsen/CZXing#77]
![1111](https://user-images.githubusercontent.com/19485318/69226213-c0853780-0bba-11ea-9be6-7615fbedcca5.png)
![2222](https://user-images.githubusercontent.com/19485318/69226215-c11dce00-0bba-11ea-98e5-53f854f433f4.png)
群里和大神说过。

**Comment by devilsen** [comment]
已解决『反色二维码』
