### ISSUE TITLE
扫投影出来的二维码，在灯光较亮的情况下识别效率不高

### ISSUE THREAD

**Issue by zyp790100288** [devilsen/CZXing#78]
扫投影出来的二维码，在灯光较亮的情况下识别效率不高。
正常情况下识别都挺快的

**Comment by devilsen** [comment]
可以拍一下当时的情况，这样描述我也不知道啥样呀

**Comment by zyp790100288** [comment]
不好意思，图片补充了

**Comment by zyp790100288** [comment]
![Screenshot_2019-11-28-13-42-00-197_com alibaba android rimet](https://user-images.githubusercontent.com/19699644/69779984-e6c35c80-11e4-11ea-8932-1c9354671139.jpg)
![Screenshot_2019-11-28-13-42-03-831_com alibaba android rimet](https://user-images.githubusercontent.com/19699644/69779985-e6c35c80-11e4-11ea-9cff-78e2a8d86ece.jpg)

**Comment by devilsen** [comment]
额。测试感觉还可以的呀

**Comment by zyp790100288** [comment]
0.9.8的版本扫不出来，0.9.10集成的可以，我再测一下现场扫的情况
