### ISSUE TITLE
设置BarcodeFormat后二维码无法扫描

### ISSUE THREAD

**Issue by zyp790100288** [devilsen/CZXing#79]
BarcodeFormat[] formats = new BarcodeFormat[]{BarcodeFormat.QR_CODE,
                BarcodeFormat.CODABAR,
                BarcodeFormat.CODE_128,
                BarcodeFormat.EAN_13,
                BarcodeFormat.CODE_93,
                BarcodeFormat.CODE_39};
  mScanView.setBarcodeFormat(formats);
设置后无法扫描二维码

        BarcodeFormat[] formats = new BarcodeFormat[]{
                BarcodeFormat.QR_CODE,
                BarcodeFormat.CODE_128,
                BarcodeFormat.CODE_93,
                BarcodeFormat.CODE_39};
        mScanView.setBarcodeFormat(formats);
设置后二维码扫描速度很慢，甚至扫不出来

**Comment by devilsen** [comment]
确实有这个问题，下个版本改一下

**Comment by devilsen** [comment]
已修复
