### ISSUE TITLE
可能导致上传google paly支持设备0

### ISSUE THREAD

**Issue by dingxiaowu** [devilsen/CZXing#84]
CZXing/czxing/src/main/AndroidManifest.xml中 
<uses-feature android:name="android.hardware.mCamera" />这句导致上传google支持设备0，是不是要改成<uses-feature android:name="android.hardware.camera" />，或者是不是我这边有问题

**Comment by devilsen** [comment]
应该是camera的声明错了，稍等修正一下

**Comment by devilsen** [comment]
已修复
