### ISSUE TITLE
混淆怎么配置？

### ISSUE THREAD

**Issue by ithomasoft** [devilsen/CZXing#85]
大神好，在引用包之后 api 'me.devilsen:CZXing:0.9.12'，开混淆出错

**Comment by zhangwenxiang26** [comment]
在你的混淆文件加上下面代码试试
-keep class me.devilsen.czxing.**
-keep class me.devilsen.czxing.** { *; }

**Comment by zhangwenxiang26** [comment]
@ithomasoft

**Comment by ithomasoft** [comment]
> @ithomasoft



> 在你的混淆文件加上下面代码试试
> -keep class me.devilsen.czxing.**
> -keep class me.devilsen.czxing.** { *; }

我试试

**Comment by ithomasoft** [comment]
可以，谢谢

**Comment by ithomasoft** [comment]
> 在你的混淆文件加上下面代码试试
> -keep class me.devilsen.czxing.**
> -keep class me.devilsen.czxing.** { *; }

可以，谢谢

**Comment by ithomasoft** [comment]
大神，可不可以把混淆加在readme里？给新接触的人一些提示

**Comment by devilsen** [comment]
会的，顺便晚上整体测试一下
