### ISSUE TITLE
扫描异常崩溃

### ISSUE THREAD

**Issue by zyp790100288** [devilsen/CZXing#88]
SIGBUS(BUS_ADRALN)

#00 lr 00000000000c3210 /data/app/com.Intretech.app.iAssistantU7-1ZhDbwks2kGiD2wCfoHS3w==/lib/arm64/libczxing.so (SafeQueue<FrameData>::enQueue(FrameData)+148) [arm64-v8a]
--
2 java:
3 me.devilsen.czxing.code.BarcodeReader.read(Unknown Source:18)
4 com.Intretech.app.iAssistant.qr.MyScanView.onPreviewFrame(Unknown Source:17)
5 com.Intretech.app.iAssistant.qr.BarCoderView.scanDataStrategy(Unknown Source:47)
6 com.Intretech.app.iAssistant.qr.BarCoderView.onPreviewFrame(Unknown Source:99)
7 android.hardware.Camera$EventHandler.handleMessage(Camera.java:1512)
8 android.os.Handler.dispatchMessage(Handler.java:106)
9 android.os.Looper.loop(Looper.java:192)
10 android.app.ActivityThread.main(ActivityThread.java:6738)
11 java.lang.reflect.Method.invoke(Native Method)
12 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
13 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)

**Comment by devilsen** [comment]
不用放在子进程处理，C++已经在子进程了

**Comment by zyp790100288** [comment]
onPreviewFrame中打印的线程还是在主线程中，没有放在子线程

**Comment by zhuxiaole** [comment]
确实，在主线程中执行也会偶尔发生这个异常

**Comment by devilsen** [comment]
fix https://github.com/devilsen/CZXing/commit/1cc7e09ac1b7c4a7f71f17f90216192cd037d613
