### ISSUE TITLE
黑边检测

### ISSUE THREAD

**Issue by KrioWly** [devilsen/CZXing#9]
如果二维码周围有一圈黑色就无法识别了？请问这种情况有什么解决方案吗？

**Comment by devilsen** [comment]
具体是什么样的黑边，需要具体看下

**Comment by KrioWly** [comment]
![avatar](F:\二维码定位\test17.jpg)

**Comment by KrioWly** [comment]
我这边图片上传有问题，问题是二维码周围是黑色的，或者接近，这样会导致二维码二值化前后没什么变化，周围都是黑的（正常的二维码周围都是有一圈留白的），这样就导致找不到1:1:3:1:1的关系，zxing没法定位pattern点，从而无法识别

**Comment by devilsen** [comment]
> 我这边图片上传有问题，问题是二维码周围是黑色的，或者接近，这样会导致二维码二值化前后没什么变化，周围都是黑的（正常的二维码周围都是有一圈留白的），这样就导致找不到1:1:3:1:1的关系，zxing没法定位pattern点，从而无法识别

确实，程序的使用还是有一点的基本需求的，如果不能解决这样的问题，我们只能从其他角度入手，另辟蹊径了。

**Comment by KrioWly** [comment]
因为我觉得可能光从二值化的方法去做应该是不行的，你用findContours的方法如果把条件降低，也能找到定位点，但是这样框出来的外接矩阵的大小可能就不能包含二维码的位置，所以是不是需要找到更加精确的定位方法，这样就可以这准确的用zxing的方法识别，希望可以给个思考方向
