### ISSUE TITLE
扫码后立即拍照

### ISSUE THREAD

**Issue by deboLing** [devilsen/CZXing#94]
我有个需求是扫码后立即拍照，所以需要改源码，但是源码需要安装ndk，接入起来太麻烦了。
可否将c部分打包为so库，使用起来方便些？

**Comment by devilsen** [comment]
可以通过[这个](https://maven.aliyun.com/repository/jcenter/me/devilsen/CZXing/0.9.13/CZXing-0.9.13.aar)下载aar，解压之后就能找到so文件；或者引用一下CZXing，在本地的 .gradle\caches\modules-2\files-2.1\me.devilsen 路径下找到aar文件，一样可以解压使用。
