### ISSUE TITLE
扫码页面初始化错误

### ISSUE THREAD

**Issue by laujiangtao** [devilsen/CZXing#96]
魅族M8s/三星j5ltezm，多次重复开启扫码页面容易出现扫码页面黑屏

W/CameraBase: An error occurred while connecting to camera 0: Service not available
W/System.err: java.lang.RuntimeException: Fail to connect to camera service
W/System.err:     at android.hardware.Camera.<init>(Camera.java:761)
W/System.err:     at android.hardware.Camera.open(Camera.java:593)
W/System.err:     at me.devilsen.czxing.view.BarCoderView.startCameraById(BarCoderView.java:202)
W/System.err:     at me.devilsen.czxing.view.BarCoderView.openCamera(BarCoderView.java:170)
W/System.err:     at me.devilsen.czxing.view.ScanView.openCamera(ScanView.java:23)
W/System.err:     at me.devilsen.czxing.view.BarCoderView.openCamera(BarCoderView.java:161)
W/System.err:     at me.devilsen.czxing.view.ScanView.openCamera(ScanView.java:23)
W/System.err:     at me.devilsen.czxing.ScanActivity.onStart(ScanActivity.java:84)
W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
W/System.err:     at android.app.Activity.performStart(Activity.java:6709)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2847)
W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
W/System.err:     at android.os.Looper.loop(Looper.java:203)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6335)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1097)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:951)
E/onOpenCameraError: onOpenCameraError

**Comment by devilsen** [comment]
其他手机上出现过吗？

**Comment by laujiangtao** [comment]
手边华为MTMT7-TL00，小米Max，Pixel1/3，三星s7/8/9/10都没出现
上面 魅族M8s 应该是 美图M8s，抱歉
