### ISSUE TITLE
app工程下有ndk { abiFilters "armeabi", "armeabi-v7a", "arm64-v8a","arm64-v8a"}，但是打包之后没有"armeabi"的so文件加入到apk,导致运行时找不到.so文件

### ISSUE THREAD

**Issue by JianfeiMa** [devilsen/CZXing#99]
app工程下有ndk { abiFilters "armeabi", "armeabi-v7a", "arm64-v8a","arm64-v8a"}，但是打包之后没有"armeabi"的so文件加入到apk,导致运行时找不到.so文件

在czxing库的gradle文件尝试加入如下abiFilters "armeabi", "armeabi-v7a","arm64-v8a"，报下面的错误，请问如何解决，非常感激

ERROR: ABIs [armeabi] are not supported for platform. Supported ABIs are [arm64-v8a, armeabi-v7a, x86, x86_64].

**Comment by devilsen** [comment]
因为这个库调用到了zbar和OpenCV的so，但是没有他们的armeabi，所以运行在这些版本的机器上是会出现问题的，如果只包含armeabi-v7a和arm64-v8a的是可以的。

**Comment by JianfeiMa** [comment]
好的，非常感谢
